# Generated by Django 5.0.1 on 2024-01-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://source.unsplash.com/random/?placeholder', max_length=600),
        ),
    ]
